### ISSUE TITLE
Starting Allora with redis should properly delete all job keys

### ISSUE THREAD

**Issue by chenkirk** [flippa/allora#2]
Upon creating a new redis backend, the reset! method call is looping through the job keys to delete the jobs, but the actual deletion incorrectly modifies the key again with `job_info_key(k)`.

https://github.com/flippa/allora/blob/master/lib/allora/backend/redis.rb#L80

This is the line in question

    redis.keys(job_info_key("*")).each { |k| redis.del(job_info_key(k)) }

Since `redis.keys` already gives the full name of the keys, we should just call `redis.del(k)` instead of `redis.del(job_info_key(k))`.

I'd be happy to create a pull request for this.

**Comment by chenkirk** [comment]
Actually there's the PR... kinda needed this :)

**Comment by ags** [comment]
Closed by https://github.com/flippa/allora/pull/3, thanks!
